name: build

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: build
      run: xmake -y -vD
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          build
