name: build

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: build
      run: xmake -y -vD
    - uses: skx/github-action-publish-binaries@release-1.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: '*'
